### ISSUE TITLE
如何修改清晰度？

### ISSUE THREAD

**Issue by zhixiangyuan** [AbelLee-LiYe/Bilibili-Download-Util#1]
大佬，修改程序的什么地方能够影响到清晰度？

**Comment by ye59080125** [comment]
对不起，现在这个不能用了，没时间更新。

**Comment by ye59080125** [comment]
> 大佬，修改程序的什么地方能够影响到清晰度？

对不起，现在这个过期不能用了，最近工作忙，没时间更新。

这个之前的清晰度，因为配置了cookie，所以是根据此cookie绑定的账号的默认观看视频清晰度来选择的。
